export const subjectTitle = {
  eng: "English Language",
  math: "Mathematics",
  bstit: "Information Technology",
  bs: "Basic Science",
  bstbs: "Basic Science",
  rnvce: "Civic Education",
  rnvse: "Security Education",
  rnvcrs: "Christian Religious Studies",
  agr_sc: "Agricultural Science",
  pvsagr: "Agricultural Science",
  pvshe: "Home Economics",
  food: "Food & Nutrition",
  bt: "Basic Technology",
  ce: "Civic Education",
  hand: "Hand Writing",
  heaha: "Health Habits",
  lite: "Literacy",
  nume: "Numeracy",
  phon: "Phonetics",
  bstphe: "Physical & Health Education",
  qr: "Quantitative Reasoning",
  rhy: "Rhymes",
  sosha: "Social Habits",
  vr: "Verbal Reasoning",
  cca: "Cutural & Creative Arts",
  comp: "Computer",
  reknow: "Religious Knowledge",
  he: "Home Economics",
  sos: "Social Studies",
  phe: "Physical & Health Education",
  yoruba: "Yoruba Language",
  se: "Security Education",
  french: "French",
  lit: "Literature-in-English",
  comm: "Commerce",
  govt: "Government",
  vocap: "Vocational Aptitude",
  current: "Current Affairs",
  moral: "Moral Instruction",
  market: "Marketing",
  bio: "Biology",
  crs: "Christian Religious Studies",
  econ: "Economics",
  phy: "Physics",
  chem: "Chemistry",
  fmath: "Further Mathematics",
  geog: "Geography",
  f_acc: "Financial Accounting",
};
